
services:
  db:
    image: percona:5.7
    container_name: "sql"
    environment:
      - MYSQL_DATABASE=${DB}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}

    ports:
      - "3306:3306"
